from typing import Protocol
from uuid import UUID

from cafe_manager.domain.entities.people import Client, Employee
from cafe_manager.domain.entities.equipment import Table, Chair, CoffeeMachine
from cafe_manager.domain.entities.menu import Ingredient, MenuItem
from cafe_manager.domain.entities.finance import Account
from cafe_manager.domain.entities.order import Order


class EmployeeRepo(Protocol):
    def get_most_free(self) -> Employee: ...

    def get_by_id(self, employee_id: UUID) -> Employee | None: ...

    def save(self, employee: Employee) -> None: ...


class FinanceRepo(Protocol):
    def get_by_id(self, account_id: UUID) -> Account | None: ...

    def save(self, account: Account) -> None: ...


class TableRepo(Protocol):
    def get_all(self) -> list[Table]: ...

    def get_by_id(self, table_id: int) -> Table | None: ...

    def save_many(self, table: list[Table]) -> None: ...


class ChairRepo(Protocol):
    def get_free(self) -> list[Chair] | None: ...

    def get_occupied_by_table_id(self, table_id: int) -> list[Chair] | None: ...

    def save_many(self, chairs: list[Chair]) -> None: ...


class InventoryRepo(Protocol):
    def get_by_names(self, names: set[str]) -> dict[Ingredient, float] | None: ...

    def save_many(self, inventory: dict[Ingredient, float]) -> None: ...


class OrderRepo(Protocol):
    def get_by_id(self, order_id: UUID) -> Order | None: ...

    def get_oldest_paid(self) -> Order | None: ...

    def get_paid_from_oldest(self) -> list[Order] | None: ...

    def save(self, order: Order) -> None: ...


class CoffeeMachineRepo(Protocol):
    def get_free(self) -> CoffeeMachine | None: ...

    def save(self, machine: CoffeeMachine) -> None: ...


class MenuRepo(Protocol):
    def get_by_names(self, names: set[str]) -> set[MenuItem] | None: ...

    def save(self, menu_item: MenuItem) -> None: ...


class ClientRepo(Protocol):
    def get_by_id(self, client_id: str) -> Client | None: ...

    def save(self, client: Client) -> None: ...
