from typing import Protocol
from uuid import UUID

from cafe_manager.domain.entities.people import Employee
from cafe_manager.domain.entities.equipment import Table, Chair, CoffeeMachine
from cafe_manager.domain.entities.menu import Ingredient, MenuItem
from cafe_manager.domain.entities.finance import Account
from cafe_manager.domain.entities.order import Order


class EmployeeRepo(Protocol):
    def get_most_free(self) -> Employee: ...

    def get_by_id(self, employee_id: UUID) -> Employee: ...

    def save(self, employee: Employee) -> None: ...


class FinanceRepo(Protocol):
    def get_by_id(self, account_id: UUID) -> Account: ...

    def save(self, account: Account) -> None: ...


class TableRepo(Protocol):
    def get_all(self) -> list[Table]: ...

    def get_by_id(self, table_id: int) -> Table: ...

    def save_many(self, table: list[Table]) -> None: ...


class ChairRepo(Protocol):
    def get_free(self) -> list[Chair]: ...

    def get_occupied_by_table_id(self, table_id: int) -> list[Chair]: ...

    def save(self, chairs: list[Chair]) -> None: ...


class InventoryRepo(Protocol):
    def get_by_names(self, names: set[str]) -> dict[Ingredient, float]: ...

    def save_many(self, inventory: dict[Ingredient, float]) -> None: ...


class OrderRepo(Protocol):
    def get_by_id(self, order_id: UUID) -> Order: ...

    def get_oldest_paid(self) -> Order: ...

    def get_paid_from_oldest(self) -> list[Order]: ...

    def save(self, order: Order) -> None: ...
    
class CoffeeMachineRepo(Protocol):
    ...


class MenuRepo(Protocol):
    def get_by_names(self, names: set[str]) -> list[MenuItem]: ...
    
    def save(self, menu_item: MenuItem) -> None: ...
